mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=pmu
    - MYSQL_USER=pmu
    - MYSQL_PASSWORD=pmu
  ports:
   - 3406:3306
crawler:
  image: node
  volumes:
    - .:/usr/src/app
  working_dir: /usr/src/app
  entrypoint:
    - node
    - index.js
  links:
    - mysql
npm:
  image: node
  volumes:
    - .:/usr/src/app
  working_dir: /usr/src/app
  entrypoint:
    - npm
  command: install
datamysql:
  image: busybox
  volumes:
    - /var/lib/mysql




