mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=pmu
    - MYSQL_USER=pmu
    - MYSQL_PASSWORD=pmu
  ports:
   - 3406:3306
app:
  build: ./docker/php
  volumes:
    - .:/usr/src/app
  links:
    - mysql

datamysql:
  image: busybox
  volumes:
    - /var/lib/mysql




